language: java
jdk:
  - oraclejdk7

branches:
  only:
    - master

#env:
#  global:
#    - secure: "0BGkXRYeLj1p9v+kcINyjSlDAPUtXFQmBbNM8B7flz/nJ9A9FoDBQVlMJ8/R1zcKmj+vPGNXRVT+rEdTiV8VlhVXAz392MHENvk//5nRynI2DuagGB4/nMf13RsHXm1mbRfR1mGZ/ZJFxB4lxZuKH5aEM3DO97ZxDEQIAv0KHdQ="
#    - secure: "yuyjzSnXLaBJbEiGzYpNxLKbHlmupwEqhMmm6YGmnxhXc5ZXPq3WVlgyEhFhIYhCvdl7ShIfkw+lPseA/gax0jFJKEPCbZoJRX/WsgAKO30dzL53BdCZasAMf5Sj77/jEUpNmzOjupNrTKQ0cuX+bNALi8iizc/9Zm/2XR50+AY="

after_success:
  - mvn clean deploy --settings settings.xml
